### ISSUE TITLE
 python-numpy error on ubuntu 16.10

### ISSUE THREAD

**Issue by wormwang** [riscv/riscv-poky#17]
Hi! guy
  I am building risc-v poky on Ubuntu 16.10. 
 I meet a error when building python-numpy. Pls help me on the error log that attached 
[log.do_install.17327.zip](https://github.com/riscv/riscv-poky/files/684117/log.do_install.17327.zip)

I built them on 16.04 successfully at before.

**Comment by sorear** [comment]
Searching the error message ( https://patchwork.openembedded.org/patch/123001/ ) there seems to be a problem with the old version of poky and new glibcs.  Did you try the `priv-1.9` branch?  It has a newer poky.

**Comment by wormwang** [comment]
I git clone latest riscv-poky, I saw it is poky "2.0+snapshot-20170105"

Build Configuration:
BB_VERSION        = "1.28.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-16.10"
TARGET_SYS        = "riscv64-poky-linux"
MACHINE           = "qemuriscv64"
DISTRO            = "poky-riscv"
DISTRO_VERSION    = "2.0+snapshot-20170105"
TUNE_FEATURES     = "riscv"


Ubuntu 16.10 is

ii  libc-bin 2.24-3ubuntu2                                 amd64        
GNU C Library: Binaries
ii  libc-dev-bin 2.24-3ubuntu2                                 
amd64        GNU C Library: Development binaries
ii  libc6:amd64                                     2.24-3ubuntu2

How to fix the issue in the 2.0snapshot, or the riscv-poky would rebase 
to newer Poky , such as Yocto 2.1.2/2.2?




在 2017年01月05日 05:28, sorear 写道:

**Comment by sorear** [comment]
```
git checkout priv-1.9
```
