### ISSUE TITLE
*** These critical programs are missing or too old: GNU ld

### ISSUE THREAD

**Issue by MyGithubAccount01** [riscv/riscv-poky#31]
When building riscv-poky, there is an error that GNU ld is missing or too old. 

It looks like the same issue as here: https://github.com/riscv/riscv-tools/#these-critical-programs-are-missing-or-too-old-make

Modified file: 
/home/user/riscv-poky/build/tmp/work/riscv64-poky-linux/glibc-initial/2.26-r0/git/configure
line 4812 as suggested in the above. 

I still get the same error. I gather this may need modified upstream. Is there a known fix for this?

[log.do_configure.2043.txt](https://github.com/riscv/riscv-poky/files/2203145/log.do_configure.2043.txt)

**Comment by dsalnikov** [comment]
Hi, any updates for this issue?

**Comment by MyGithubAccount01** [comment]
I don't know all the details now, but as I recall, this was a legitimate error. Ld was from Ubuntu 14.04 and it would not compile. I think ld needs to be 2.25 or higher.

I moved to a newer version of Linux and it works fine for me there.
